language: go
go_import_path: github.com/clearcontainers/proxy
go:
        - 1.7
        - tip

env:
        - secure: "cEEEvdXglEtVlycz1ZT6etM4N0uvBMV3BcAJMSUVHkq30DEqJ3Ul9LzlSTsSLQSZYLAMPvQ+MltB+tubgI7UL3lE0tnotFd+3O3DNlNpRuNGQF81Gon0PMkt4mSqXgb/OKJgdTTKXkoatSFVrp5bwYSu8Buuq6T30S29fyyKexn+MsuBBKLrIVLydHYfugcE28syGS6KErVJ8e/duW5MQNtYVS+e0T6i69I6l/jOiZpBXWdv9RXMHN0QAFN6s/PnTtmMT2XCcYDNwUdtCFrarCCbZSS6kVwbskPI3MpLZABXsSjvNcSH7vhassOKO1/7mqNrDrhD1yD7d/PQZYtST+wA/wA8pQcVCJg/t0mimBrbkrXQswf9xUbbCvKSlOfZp2gwCkp91VX0nUM3kO/0XMYHhJDh1gGOyXxWK6cuiglagMo7h5kp1m4Yl2K2G4QyoXdKufp4GOn5C3amvNHmn7rWTvEUjBGtx7iti7dqBBo/rLsyPQOA03ndTG5bVAh6d//b/RUd6ZpEPajrocG4rUdMMzMA1mvR2rtF8IJtTdFBZo+GRaPW9+KWqiOGsW0YbwQ5+fR4ydH/xsvADzrX74X/as+hRPF9oSgBBV1KQis4LG/uGISmwX38yrun3Hgwdvbfyt9B455uTHOaftwObgOvAKzjENTIfTmNNc3W3og="

script:
        - make
        - make check

after_success:
        - go get github.com/mattn/goveralls
        - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=profile.cov
